#include "bsp_boarddb_priv.h"

#include "driver/sdmmc_host.h"

const bsp_boarddb_desc_t bsp_boarddb_doers3_desc = {
    .id = BSP_BOARDDB_DOERS3,
    .name = "DoerS3",
    .capabilities = BSP_BOARDDB_CAP_IOEXP |
                    BSP_BOARDDB_CAP_DISPLAY |
                    BSP_BOARDDB_CAP_TOUCH |
                    BSP_BOARDDB_CAP_BACKLIGHT |
                    BSP_BOARDDB_CAP_SDCARD |
                    BSP_BOARDDB_CAP_IMU |
                    BSP_BOARDDB_CAP_AUDIO |
                    BSP_BOARDDB_CAP_CAMERA |
                    BSP_BOARDDB_CAP_GNSS,
    .i2c = {
        .present = true,
        .port = I2C_NUM_0,
        .sda = GPIO_NUM_1,
        .scl = GPIO_NUM_2,
        .glitch_ignore_cnt = 7,
        .enable_internal_pullup = true,
    },
    .ioexp = {
        .present = true,
        .kind = BSP_BOARDDB_IOEXP_KIND_PCA9557,
        .address = 0x19,
        .scl_speed_hz = 100000,
        .output_default = 0x05,
        .direction_mask = 0xF8,
    },
    .display = {
        .present = true,
        .kind = BSP_BOARDDB_DISPLAY_KIND_ST7789,
        .width = 320,
        .height = 240,
        .data_endian = LCD_RGB_DATA_ENDIAN_BIG,
        .invert_color = true,
        .spi_host = SPI2_HOST,
        .lcd_cs = {
            .type = BSP_BOARDDB_CTRL_PIN_IOEXP,
            .active_high = false,
            .num.ioexp_num = 0,
        },
        .lcd_dc = GPIO_NUM_39,
        .lcd_mosi = GPIO_NUM_40,
        .lcd_sclk = GPIO_NUM_41,
        .panel_reset_gpio = GPIO_NUM_NC,
        .swap_xy = true,
        .mirror_x = true,
        .mirror_y = false,
    },
    .touch = {
        .present = true,
        .kind = BSP_BOARDDB_TOUCH_KIND_FT5X06,
        .address = 0x38,
        .x_max = 239,
        .y_max = 319,
        .reset_gpio = GPIO_NUM_NC,
        .int_gpio = GPIO_NUM_NC,
        .level_reset = 0,
        .level_interrupt = 0,
        .swap_xy = true,
        .mirror_x = true,
        .mirror_y = false,
    },
    .backlight = {
        .present = true,
        .kind = BSP_BOARDDB_BACKLIGHT_KIND_LEDC,
        .gpio = GPIO_NUM_42,
        .output_invert = true,
    },
    .sdcard = {
        .present = true,
        .kind = BSP_BOARDDB_SDCARD_KIND_SDMMC,
        .clk = GPIO_NUM_47,
        .cmd = GPIO_NUM_48,
        .d0 = GPIO_NUM_21,
        .d1 = GPIO_NUM_NC,
        .d2 = GPIO_NUM_NC,
        .d3 = GPIO_NUM_NC,
        .cd = SDMMC_SLOT_NO_CD,
        .wp = SDMMC_SLOT_NO_WP,
        .width = 1,
        .slot_flags = SDMMC_SLOT_FLAG_INTERNAL_PULLUP,
        .max_freq_khz = SDMMC_FREQ_DEFAULT,
        .format_if_mount_failed = false,
        .max_files = 5,
        .disk_status_check_enable = false,
        .use_one_fat = false,
    },
    .imu = {
        .present = true,
        .address = 0x6A,
        .accel_unit_mps2 = true,
        .gyro_unit_rads = true,
        .display_precision = 4,
    },
    .audio = {
        .present = true,
        .has_playback = true,
        .has_record = true,
        .i2s_port = I2S_NUM_0,
        .mclk = GPIO_NUM_38,
        .bclk = GPIO_NUM_14,
        .ws = GPIO_NUM_13,
        .dout = GPIO_NUM_45,
        .din = GPIO_NUM_12,
        .es8311_addr = 0x30,
        .es7210_addr = 0x82,
        .es7210_mic_mask = 0x07,
        .pa_enable = {
            .type = BSP_BOARDDB_CTRL_PIN_IOEXP,
            .active_high = true,
            .num.ioexp_num = 1,
        },
        .use_mclk = true,
        .mclk_multiple = 256,
    },
    .camera = {
        .present = true,
        .pwdn = {
            .type = BSP_BOARDDB_CTRL_PIN_IOEXP,
            .active_high = true,
            .num.ioexp_num = 2,
        },
        .reset = GPIO_NUM_NC,
        .xclk = GPIO_NUM_5,
        .d7 = GPIO_NUM_9,
        .d6 = GPIO_NUM_4,
        .d5 = GPIO_NUM_6,
        .d4 = GPIO_NUM_15,
        .d3 = GPIO_NUM_17,
        .d2 = GPIO_NUM_8,
        .d1 = GPIO_NUM_18,
        .d0 = GPIO_NUM_16,
        .vsync = GPIO_NUM_3,
        .href = GPIO_NUM_46,
        .pclk = GPIO_NUM_7,
        .xclk_freq_hz = 24000000,
        .pixel_format = PIXFORMAT_RGB565,
        .frame_size = FRAMESIZE_QVGA,
        .jpeg_quality = 12,
        .fb_count = 2,
        .fb_location = CAMERA_FB_IN_PSRAM,
        .grab_mode = CAMERA_GRAB_WHEN_EMPTY,
        .enable_hmirror = true,
        .enable_vflip = false,
    },
    .gnss = {
        .present = true,
        .kind = BSP_BOARDDB_GNSS_KIND_ATGM336H,
        .uart_port = UART_NUM_1,
        .tx_pin = GPIO_NUM_11,
        .rx_pin = GPIO_NUM_10,
        .baud_rate = 9600,
        .rx_buffer_size = 2048,
        .read_timeout_ms = 200,
    },
};
