#pragma once

#include "driver/gpio.h"
#include "driver/i2c_types.h"
#include "driver/i2s_types.h"
#include "driver/spi_master.h"
#include "driver/uart.h"
#include "driver/sdmmc_types.h"

#define DOERS3_I2C_PORT I2C_NUM_0
#define DOERS3_I2C_SDA GPIO_NUM_1
#define DOERS3_I2C_SCL GPIO_NUM_2
#define DOERS3_I2C_GLITCH_IGNORE_CNT 7
#define DOERS3_I2C_INTERNAL_PULLUP 1

#define DOERS3_IMU_I2C_ADDR 0x6A

#define DOERS3_AUDIO_I2S_PORT I2S_NUM_0
#define DOERS3_AUDIO_I2S_MCLK GPIO_NUM_38
#define DOERS3_AUDIO_I2S_BCLK GPIO_NUM_14
#define DOERS3_AUDIO_I2S_WS GPIO_NUM_13
#define DOERS3_AUDIO_I2S_DOUT GPIO_NUM_45
#define DOERS3_AUDIO_I2S_DIN GPIO_NUM_12
#define DOERS3_AUDIO_ES8311_ADDR_7BIT 0x18
#define DOERS3_AUDIO_ES7210_ADDR_7BIT 0x41

#define DOERS3_IOEXP_I2C_ADDR 0x19
#define DOERS3_IOEXP_SPEED_HZ 100000
#define DOERS3_IOEXP_OUTPUT_DEFAULT 0x05
#define DOERS3_IOEXP_DIRECTION_MASK 0xF8
#define DOERS3_IOEXP_LCD_CS 0
#define DOERS3_IOEXP_AUDIO_PA 1
#define DOERS3_IOEXP_AUDIO_PA_ENABLE_LEVEL 1
#define DOERS3_IOEXP_CAMERA_PWDN 2

#define DOERS3_LCD_WIDTH 320
#define DOERS3_LCD_HEIGHT 240
#define DOERS3_LCD_SPI_HOST SPI2_HOST
#define DOERS3_LCD_DC GPIO_NUM_39
#define DOERS3_LCD_MOSI GPIO_NUM_40
#define DOERS3_LCD_SCLK GPIO_NUM_41
#define DOERS3_LCD_RESET GPIO_NUM_NC

#define DOERS3_TOUCH_ADDR 0x38
#define DOERS3_TOUCH_X_MAX 239
#define DOERS3_TOUCH_Y_MAX 319
#define DOERS3_TOUCH_RESET GPIO_NUM_NC
#define DOERS3_TOUCH_INT GPIO_NUM_NC

#define DOERS3_BACKLIGHT_GPIO GPIO_NUM_42
#define DOERS3_BACKLIGHT_OUTPUT_INVERT 1

#define DOERS3_SDCARD_CLK GPIO_NUM_47
#define DOERS3_SDCARD_CMD GPIO_NUM_48
#define DOERS3_SDCARD_D0 GPIO_NUM_21

#define DOERS3_GNSS_UART UART_NUM_1
#define DOERS3_GNSS_TX GPIO_NUM_11
#define DOERS3_GNSS_RX GPIO_NUM_10
#define DOERS3_GNSS_BAUD 38400
#define DOERS3_GNSS_RX_BUFFER_SIZE 2048
